name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests for just scenario with feature A regex
      run: npx playwright test --grep ^with-feature-A$
      continue-on-error: true
    - name: Run Playwright tests for just scenario with feature B regex
      run: npx playwright test --grep ^with-feature-B$
      continue-on-error: true
    - name: Run Playwright tests for just scenario with feature A and B regex
      run: npx playwright test --grep ^with-feature-A-and-B$
      continue-on-error: true
    - name: Run Playwright tests for just scenario with feature A
      run: npx playwright test --grep with-feature-A
      continue-on-error: true
    - name: Run Playwright tests for just scenario with feature B
      run: npx playwright test --grep with-feature-B
      continue-on-error: true
    - name: Run Playwright tests for just scenario with feature A and B
      run: npx playwright test --grep with-feature-A-and-B
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
