name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-scenario:
          - with-feature-A
          - with-feature-B
          - with-feature-A-and-B
    steps:
    - uses: actions/checkout@v4
    - name: Deploy application
      run: echo "Deploying application with configuration for ${{ matrix.test-scenario}}"
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests with regex anchors
      run: npx playwright test --grep ^${{ matrix.test-scenario }}$
      continue-on-error: true
    - name: Run Playwright tests with regex ending anchors
      run: npx playwright test --grep ${{ matrix.test-scenario }}$
      continue-on-error: true
    - name: Run Playwright tests
      run: npx playwright test --grep ${{ matrix.test-scenario }}
      continue-on-error: true
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.test-scenario}}-playwright-report
        path: playwright-report/
        retention-days: 30
